name: "[SERVER] lint, compile TS"

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server.yml"
  pull_request:
    types: ["opened", "edited", "synchronize"]
    paths:
      - "server/**"
      - ".github/workflows/server.yml"

jobs:
  lint-build:
    name: lint and compile TS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn lint
      - run: yarn ts
